Update StakingPool.sol
energywebfoundation/iam-contracts pull request #46
Opened 2021-08-01 20:33 UTC by ayoubhr

Changes made in lines 120 and 124:

To avoid interfering with quotations.

2021-08-01 20:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/energywebfoundation/iam-contracts?pullRequest=46) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/energywebfoundation/iam-contracts?pullRequest=46) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/energywebfoundation/iam-contracts?pullRequest=46) it.</sub>

2021-08-03 08:17 UTC, JGiter approved these changes

2021-08-03 09:45 UTC, knzeng-e approved these changes

2021-08-03 09:49 UTC, ahmedolaibrahim approved these changes

2021-08-03 17:54 UTC, jrhender approved these changes

2021-08-05 15:44 UTC, jrhender requested changes
Please adjust the tests as well so that all tests are passing. Test can be run locally using `npm test`

2022-01-11 08:13 UTC, closed without merging